name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get npm cache directory path
        id: npm-cache-dir
        run: echo "NPM_CACHE_DIR=$(npm config get cache)" >> $GITHUB_ENV

      - name: Cache node_modules and npm cache
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            ${{ env.NPM_CACHE_DIR }}
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm install
